trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self # Check out the Azure DevOps repo

  - script: |
      # Fetch the main branch explicitly
      git fetch origin main

      # Ensure the main branch is checked out
      git checkout main

      # Set up the GitHub remote with authentication
      git remote add github https://$(GITHUB_USERNAME):$(GITHUB_PAT)@github.com/gnaudio/jabra-dotnet-device-properties-sample.git

      # Push the main branch to the GitHub remote
      git push github main

    displayName: "Push to GitHub - PUBLIC REPO"
