trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    fetchDepth: 0  # fetch full history from the ADO repo

  - script: |
      # Set up the GitHub remote with authentication
      git remote add github https://$(GITHUB_USERNAME):$(GITHUB_PAT)@github.com/gnaudio/jabra-dotnet-device-properties-sample.git

      # Push the main branch to the GitHub remote
      git push github main

    displayName: "Push to GitHub - PUBLIC REPO"
